using System;
using System.Xml;

class Program
{
    static void MainExample(string[] args)
    {
        // Create the XmlDocument object.
        XmlDocument xmlDoc = new XmlDocument();

        // Create the XML declaration.
        XmlDeclaration xmlDeclaration = xmlDoc.CreateXmlDeclaration("1.0", "UTF-8", null);

        // Add the XML declaration to the document.
        xmlDoc.AppendChild(xmlDeclaration);

        // Create the root element.
        XmlElement root = xmlDoc.CreateElement("document");
        xmlDoc.AppendChild(root);

        // Create the title element and add it to the root.
        XmlElement title = xmlDoc.CreateElement("title");
        title.InnerText = "My Simple XmlDoc File";
        root.AppendChild(title);

        // Create the description element and add it to the root.
        XmlElement description = xmlDoc.CreateElement("description");
        description.InnerText = "This is a simple XmlDoc file generated by ChatGPT";
        root.AppendChild(description);

        // Create the body element and add it to the root.
        XmlElement body = xmlDoc.CreateElement("body");
        root.AppendChild(body);

        // Create the first section element and add it to the body.
        XmlElement section1 = xmlDoc.CreateElement("section");
        body.AppendChild(section1);

        // Create the heading element for section 1 and add it to the section.
        XmlElement section1Heading = xmlDoc.CreateElement("heading");
        section1Heading.InnerText = "Section 1";
        section1.AppendChild(section1Heading);

        // Create the content element for section 1 and add it to the section.
        XmlElement section1Content = xmlDoc.CreateElement("content");
        section1Content.InnerText = "This is the content of section 1";
        section1.AppendChild(section1Content);

        // Create the second section element and add it to the body.
        XmlElement section2 = xmlDoc.CreateElement("section");
        body.AppendChild(section2);

        // Create the heading element for section 2 and add it to the section.
        XmlElement section2Heading = xmlDoc.CreateElement("heading");
        section2Heading.InnerText = "Section 2";
        section2.AppendChild(section2Heading);

        // Create the content element for section 2 and add it to the section.
        XmlElement section2Content = xmlDoc.CreateElement("content");
        section2Content.InnerText = "This is the content of section 2";
        section2.AppendChild(section2Content);

        // Save the XmlDoc file to disk.
        xmlDoc.Save("myxmldoc.xml");

        Console.WriteLine("XmlDoc file saved successfully!");
    }
}
