using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace XMLpad
{
    /// <summary>
    /// Interaction logic for ManualWindow.xaml
    /// </summary>
    public partial class ManualWindow : Window
    {
        public ManualWindow()
        {
            InitializeComponent();
        }

        private void Hyperlink_RequestNavigate(object sender, System.Windows.Navigation.RequestNavigateEventArgs e)
        {
            System.Diagnostics.Process.Start(new ProcessStartInfo
            {
                FileName = "https://github.com/MaykalDroshev-Hull/XMLpad",
                UseShellExecute = true
            });
        }

        /// <summary>
        /// Handles the Click event of the CloseButton control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="RoutedEventArgs"/> instance containing the event data.</param>
        private void CloseButton_Click(object sender, RoutedEventArgs e) => Close();


        /// <summary>
        /// Invoked when an unhandled <see cref="E:System.Windows.UIElement.MouseLeftButtonDown" /> routed event is raised on this element. Implement this method to add class handling for this event.
        /// </summary>
        /// <param name="e">The <see cref="T:System.Windows.Input.MouseButtonEventArgs" /> that contains the event data. The event data reports that the left mouse button was pressed.</param>
        protected override void OnMouseLeftButtonDown(MouseButtonEventArgs e)
        {
            base.OnMouseLeftButtonDown(e);

            // Begin dragging the window
            this.DragMove();
        }

        private void TreeView_SelectedItemChanged(object sender, RoutedPropertyChangedEventArgs<object> e)
        {
            TreeViewItem selectedItem = (TreeViewItem)manualTreeView.SelectedItem;
            string header = selectedItem.Header as string;
            switch (header)
            {
                case "New":
                    explanationTextBlock.Text = "The 'New' command creates a new file in the current directory. This file is typically blank, but can be pre-populated with default content depending on the application or operating system being used. The new file will have a unique file name that can be specified by the user or automatically generated by the system.";
                    break;
                case "Clear":
                    explanationTextBlock.Text = "The 'Clear' command clears the contents of the current file, effectively deleting all the data stored within it.";
                    break;
                case "Open":
                    explanationTextBlock.Text = "The 'Open' command opens an existing file.";
                    break;
                case "Save":
                    explanationTextBlock.Text = "The 'Save' command saves the current file.";
                    break;
                case "Save As":
                    explanationTextBlock.Text = "The 'Save As' command saves the current file with a different name or location.";
                    break;
                case "Save A Copy As":
                    explanationTextBlock.Text = "The 'Save A Copy As' command saves a copy of the current file with a different name or location.";
                    break;
                case "Print":
                    explanationTextBlock.Text = "The 'Print' command prints the current file.";
                    break;
                case "Compare File With Another":
                    explanationTextBlock.Text = "The 'Compare File With Another' saves and compares the current file with another file chosen immediately after pressing the button.";
                    break;
                case "Exit":
                    explanationTextBlock.Text = "The 'Exit' command closes the application.";
                    break;
                case "Undo":
                    explanationTextBlock.Text = "The 'Undo' command undoes the last action.";
                    break;
                case "Redo":
                    explanationTextBlock.Text = "The 'Redo' command redoes the last undone action.";
                    break;
                case "Cut":
                    explanationTextBlock.Text = "The 'Cut' command cuts the selected text.";
                    break;
                case "Copy":
                    explanationTextBlock.Text = "The 'Copy' command copies the selected text.";
                    break;
                case "Paste":
                    explanationTextBlock.Text = "The 'Paste' command pastes the copied or cut text.";
                    break;
                case "Delete":
                    explanationTextBlock.Text = "The 'Delete' command deletes the selected text.";
                    break;
                case "Select All":
                    explanationTextBlock.Text = "The 'Select All' command selects all the text in the current file.";
                    break;
                case "Date Time (Short)":
                    explanationTextBlock.Text = "The 'Date Time (Short)' command inserts the current date and time in a short format.";
                    break;
                case "Date Time (Long)":
                    explanationTextBlock.Text = "The 'Date Time (Long)' command inserts the current date and time in a long format.";
                    break;
                case "Date Time (Customised)":
                    explanationTextBlock.Text = "The 'Date Time (Customised)' command inserts the current date and time in a customised format.";
                    break;
                case "Customise Date Time":
                    explanationTextBlock.Text = "The 'Customise Date Time' command allows you to customize the format of the date and time that is inserted when using the 'Date Time (Customised)' command.";
                    break;
                case "Copy Current File Path":
                    explanationTextBlock.Text = "The 'Copy Current File Path' command copies the file path of the current file to the clipboard.";
                    break;
                case "Copy Current File Name":
                    explanationTextBlock.Text = "The 'Copy Current File Name' command copies the file name of the current file to the clipboard.";
                    break;
                case "Increase Indent (+)":
                    explanationTextBlock.Text = "The 'Increase Indent (+)' command increases the indentation level of the selected text.";
                    break;
                case "Decrease Indent (-)":
                    explanationTextBlock.Text = "The 'Decrease Indent (-)' command decreases the indentation level of the selected text.";
                    break;
                case "All Uppercase":
                    explanationTextBlock.Text = "The 'All Uppercase' command converts the selected text to uppercase.";
                    break;
                case "All Lowercase":
                    explanationTextBlock.Text = "The 'All Lowercase' command converts the selected text to lowercase.";
                    break;
                case "Invert Case":
                    explanationTextBlock.Text = "The 'Invert Case' command inverts the case of the selected text.";
                    break;
                case "Random Case":
                    explanationTextBlock.Text = "The 'Random Case' command applies a random case to the selected text.";
                    break;
                case "Duplicate Line":
                    explanationTextBlock.Text = "The 'Duplicate Line' command duplicates the current line.";
                    break;
                case "Remove Duplicate Lines":
                    explanationTextBlock.Text = "The 'Remove Duplicate Lines' command removes duplicate lines from the current file.";
                    break;
                case "Remove Consecutive Duplicate Lines":
                    explanationTextBlock.Text = "The 'Remove Consecutive Duplicate Lines' command removes consecutive duplicate lines from the current file.";
                    break;
                case "Move Up The Current Line":
                    explanationTextBlock.Text = "The 'Move Up The Current Line' command moves the current line up one position.";
                    break;
                case "Move Down The Current Line":
                    explanationTextBlock.Text = "The 'Move Down The Current Line' command moves the current line down one position.";
                    break;
                case "Remove Empty Lines":
                    explanationTextBlock.Text = "The 'Remove Empty Lines' command removes empty lines from the current file.";
                    break;
                case "Insert Blank Line Above Current":
                    explanationTextBlock.Text = "The 'Insert Blank Line Above Current' command inserts a blank line above the current line.";
                    break;
                case "Insert Blank Line Below Current":
                    explanationTextBlock.Text = "The 'Insert Blank Line Below Current' command inserts a blank line below the current line.";
                    break;
                case "Comment/Uncomment":
                    explanationTextBlock.Text = "The 'Comment/Uncomment' command allows you to comment or uncomment the selected text.";
                    break;
                case "Comment":
                    explanationTextBlock.Text = "The 'Comment' command allows you to add a comment symbol at the beginning of each line in the selected text.";
                    break;
                case "Uncomment":
                    explanationTextBlock.Text = "The 'Uncomment' command allows you to remove the comment symbol at the beginning of each line in the selected text.";
                    break;
                case "Trim Trailing Space":
                    explanationTextBlock.Text = "The 'Trim Trailing Spaces' command is used to remove any unwanted whitespace characters, such as spaces or tabs, from the end of lines in the selected text. This is useful for cleaning up code and making sure that there are no unnecessary characters present. By trimming the whitespace, the code will be more readable and easier to understand.";
                    break;
                case "Trim Leading Space":
                    explanationTextBlock.Text = "The 'Trim Leading Space' command is used to remove any unwanted whitespace characters, such as spaces or tabs, from the beginning of lines in the selected text. This is useful for cleaning up code and making sure that there are no unnecessary characters present. By trimming the whitespace, the code will be more readable and easier to understand.";
                    break;
                case "Trim Trailing and Leading Space":
                    explanationTextBlock.Text = "The 'Trim Trailing and Leading Space' command is used to remove any unwanted whitespace characters, such as spaces or tabs, from both the beginning and end of lines in the selected text. This is useful for cleaning up code and making sure that there are no unnecessary characters present. By trimming the whitespace, the code will be more readable and easier to understand.";
                    break;
                case "TAB To Space":
                    explanationTextBlock.Text = "The 'TAB To Space' command is used to convert any tab characters into spaces in the selected text. This is useful for making sure that the code is properly formatted and easier to read. By converting all of the tabs to spaces, the code will be more consistent and easier to understand.";
                    break;
                case "Space to TAB(Leading)":
                    explanationTextBlock.Text = "The 'Space to TAB(Leading)' command is used to convert any leading spaces into tab characters in the selected text. This is useful for making sure that the code is properly formatted and easier to read. By converting all of the spaces to tabs, the code will be more consistent and easier to understand.";
                    break;
                case "Space To TAB(Trailing)":
                    explanationTextBlock.Text = "The 'Space to TAB(Trailing)' command is used to convert any trailing spaces into tab characters in the selected text. This is useful for making sure that the code is properly formatted and easier to read. By converting all of the spaces to tabs, the code will be more consistent and easier to understand.";
                    break;
                case "Space to TAB(All)":
                    explanationTextBlock.Text = "The 'Space to TAB(All)' command is used to convert any spaces into tab characters in the selected text, regardless of whether they are leading or trailing. This is useful for making sure that the code is properly formatted and easier to read. By converting all of the spaces to tabs, the code will be more consistent and easier to understand.";
                    break;
                case "Set As Read-Only":
                    explanationTextBlock.Text = "The 'Set As Read-Only' command is used to make the file read-only, meaning that it cannot be modified. This is useful for protecting certain parts of a document from being accidentally changed.";
                    break;
                case "Toggle Full Screen Mode":
                    explanationTextBlock.Text = "The 'Toggle Full Screen Mode' command is used to toggle between full screen and windowed mode, allowing you to make the most of your screen space. To toggle full screen mode, simply click the 'Toggle Full Screen Mode' command from the menu. The program will then switch between full screen and windowed mode.";
                    break;
                case "Syntax Highlighting":
                    explanationTextBlock.Text = "The syntax highlighting command usually has multiple options for different programming languages, and the highlighting rules for each language are defined in a syntax definition file. This file specifies which elements of the code should be highlighted and how they should be displayed. In addition to coloring, syntax highlighting can also provide code folding, which allows you to collapse blocks of code to make it easier to navigate large files. For example, you can fold all of the functions in a file so that only the function names are visible. When you need to access the code in a function, you can simply unfold it.";
                    break;
                case "Show spaces and Tabs":
                    explanationTextBlock.Text = "The 'Show Spaces and Tabs' command is used to display any whitespace characters in a document, including spaces and tabs. This is useful for debugging and for visualizing how the document is structured. To display the whitespace characters, simply click the 'Show Spaces and Tabs' command from the menu. The whitespace characters will then be highlighted and visible in the document";
                    break;
                case "Show new lines":
                    explanationTextBlock.Text = "The 'Show New Lines' command is used to display any new line characters in a document, allowing you to see where lines begin and end. To display the new line characters, simply click the 'Show New Lines' command from the menu. The new line characters will then be highlighted and visible in the document.";
                    break;
                case "Show all characters":
                    explanationTextBlock.Text = "The 'Show All Characters' command is used to display all of the characters, including whitespace, new line, and other hidden characters, in a document. To display all of the characters, simply click the 'Show All Characters' command from the menu. The characters will then be highlighted and visible in the document.";
                    break;
                case "Zoom in":
                    explanationTextBlock.Text = "The 'Zoom In' command is used to magnify the current view of a document, allowing you to see more detail. To zoom in, simply click the 'Zoom In' command from the menu or press the corresponding keyboard shortcut ('Ctrl' + '+'). The document will then be magnified, allowing you to see more detail.";
                    break;
                case "Zoom out":
                    explanationTextBlock.Text = "The 'Zoom Out' command is used to reduce the current view of a document, allowing you to see a larger area. To zoom out, simply click the 'Zoom Out' command from the menu or press the corresponding keyboard shortcut ('Ctrl' + '-'). The document will then be reduced in size, allowing you to see more of the document at once.";
                    break;
                case "Restore default zoom":
                    explanationTextBlock.Text = "The 'Restore Default Zoom' command is used to reset the view of a document to the default size. To restore the default zoom, simply click the 'Restore Default Zoom' command from the menu or press the corresponding keyboard shortcut ('Ctrl' + '0'). The document will then be reset to its default zoom level.";
                    break;
                case "Change Theme":
                    explanationTextBlock.Text = "The 'Change Theme' Command will change between the dark and the light mode of the program.";
                    break;

                case "View Manual":
                    explanationTextBlock.Text = "The View Manual commands leads to this window";
                    break;
                case "Menu Bar Commands":
                case "File Commands":
                case "Edit Commands":
                case "View":
                case "Settings":
                case "Help":
                case "Insert":
                case "Convert Case":
                case "Indent":
                case "Line Operations":
                case "Blank Operations":
                case "Show Symbol":
                case "Zoom":
                    explanationTextBlock.Text = string.Empty;
                    break;
                default:
                    explanationTextBlock.Text = "This command is not yet implemented.";
                    break;
            }
        }
    }
}

